In [2]:
import json
import xml.etree.ElementTree as ET
from collections import defaultdict
import yaml
import time as tm
import  numpy as np

In [14]:
root = ET.parse('/users/zengwei/data/DD/dynamic-domain-2016-truth-data.xml').getroot()

Truth = defaultdict(dict)    
for domain in list(root):
    
    for topic in list(domain):
        if topic.tag == 'topic':
            topic_id = topic.attrib['id']
            Truth[topic_id] = []
            Truth[topic_id].append(defaultdict(dict))
            
            n_subtopic =0
            for subtopic in list(topic):
                if subtopic.tag == 'subtopic':
                    n_subtopic += 1
                    subtopic_id = subtopic.attrib['id']
                    
                    
                    for passage in list(subtopic):
                        doc_id = passage.attrib['id']
                        
                        tmp=0
                        for tag_under_passage in list(passage):
                            if tag_under_passage.tag == 'rating':
                                rating = tag_under_passage.text
                                tmp+=1
                            if tag_under_passage.tag == 'docno':
                                doc_id = tag_under_passage.text
                        
                        if tmp==1:     
                            if  Truth[topic_id][0].has_key(doc_id):
                                Truth[topic_id][0][doc_id].append((subtopic_id, rating))
                            else:
                                Truth[topic_id][0][doc_id] = []
                                Truth[topic_id][0][doc_id].append((subtopic_id, rating))
                        else:
                            print tmp
            Truth[topic_id].append(n_subtopic)
                            
json.dump(Truth, open('/users/zengwei/data/DD/ZW_JSON/Truth.json', 'w'))

In [3]:
QueryDocs = defaultdict(dict)

for file_index in range(1, 54):
    QueryDocs['DD16-' + str(file_index)]=[]
    
    docs = json.load(open('/users/zengwei/data/DD/wxf_result/wxf_result/results/DD16-' + str(file_index) + '.json'))
    for doc in docs:
        QueryDocs['DD16-' + str(file_index)].append(doc['key'])
        
json.dump(QueryDocs, open('/users/zengwei/data/DD/ZW_JSON/All_QueryDocs.json', 'w'))

start = tm.clock()
QueryDocs = json.load(open('/users/zengwei/data/DD/ZW_JSON/All_QueryDocs.json', 'r'))
elapsed = (tm.clock() - start)
print("Time used:",elapsed)

('Time used:', 0.05000000000000071)


In [4]:
Embedfile = open('/users/zengwei/data/DD/embedding/All_200_50.yml', 'r')
Doc2Vec = defaultdict(dict)
info=''
for line in Embedfile.readlines():
    if line == '\n':
        docvec = yaml.load(info)
        Doc2Vec[docvec['tag']]=docvec['feature'].tolist()
        info = ''
    else:
        info += line       
json.dump(Doc2Vec, open('/users/zengwei/data/DD/ZW_JSON/All_200_50ite_Doc2Vec.json', 'w'))

start = tm.clock()
QueryDocs = json.load(open('/users/zengwei/data/DD/ZW_JSON/All_200_50ite_Doc2Vec.json', 'r'))
elapsed = (tm.clock() - start)
print("Time used:",elapsed)

('Time used:', 3.4799999999999898)


In [18]:
### mini_data DD-1  DD-5

# MiniData_QueryDocs
QueryDocs = defaultdict(dict)
Docs=set()

for file_index in range(1, 6):
    QueryDocs['DD16-' + str(file_index)]=[]
    
    docs = json.load(open('/users/zengwei/data/DD/wxf_result/wxf_result/results/DD16-' + str(file_index) + '.json'))
    for doc in docs:
        QueryDocs['DD16-' + str(file_index)].append(doc['key'])
        Docs.add(doc['key'])
        
json.dump(QueryDocs, open('/users/zengwei/data/DD/ZW_JSON/MiniData_QueryDocs.json', 'w'))

start = tm.clock()
QueryDocs = json.load(open('/users/zengwei/data/DD/ZW_JSON/MiniData_QueryDocs.json', 'r'))
elapsed = (tm.clock() - start)
print "Time used:",elapsed


# MiniData_200_50ite_Doc2Vec
Embedfile = open('/users/zengwei/data/DD/embedding/All_200_50.yml', 'r')
Doc2Vec = defaultdict(dict)
info=''
for line in Embedfile.readlines():
    if line == '\n':
        docvec = yaml.load(info)
        if docvec['tag'] in Docs or  docvec['tag'] in QueryDocs.keys():
            Doc2Vec[docvec['tag']]=docvec['feature'].tolist()
        info = ''
    else:
        info += line
        
print len(Doc2Vec.keys())
json.dump(Doc2Vec, open('/users/zengwei/data/DD/ZW_JSON/MiniData_200_50ite_Doc2Vec.json', 'w'))

start = tm.clock()
Doc2Vec = json.load(open('/users/zengwei/data/DD/ZW_JSON/MiniData_200_50ite_Doc2Vec.json', 'r'))
elapsed = (tm.clock() - start)
print "Time used:",elapsed

Time used: 0.0


KeyboardInterrupt: 

In [13]:
query_index = np.arange(1,54)
np.random.shuffle(query_index)
query_index = np.split(query_index,[18,36])


QueryDocs_list = []

for folds in query_index:
    
    print 'yyy'
    QueryDocs = defaultdict(dict)
    for file_index in folds:    
        QueryDocs['DD16-' + str(file_index)]=[]
        
        docs = json.load(open('/users/zengwei/data/DD/wxf_result/wxf_result/results/DD16-' + str(file_index) + '.json'))
        for doc in docs:
            QueryDocs['DD16-' + str(file_index)].append(doc['key'])
    QueryDocs_list.append(QueryDocs)
            
json.dump(QueryDocs_list, open('/users/zengwei/data/DD/ZW_JSON/All_QueryDocs_3K.json', 'w'))

print len(QueryDocs_list)
    
start = tm.clock()
QueryDocs = json.load(open('/users/zengwei/data/DD/ZW_JSON/All_QueryDocs_3K.json', 'r'))
elapsed = (tm.clock() - start)
print("Time used:",elapsed)

yyy


yyy


yyy


3
('Time used:', 0.03999999999999204)


In [11]:
query_index = np.arange(1,54)
np.random.shuffle(query_index)
print query_index

query_index = np.split(query_index,[18, 36])

for query in query_index:
    print query, len(query)

[33 35 50 21 44 52 47 19 40 34 24  5  8 46 11 30 27 38 39 45 51 23 20 12 32
  4 14 43 10 28 26 36  3 29 53  9 15 37 13 42 17 25 16 31 18  2 41 22 48  1
 49  7  6]
[33 35 50 21 44 52 47 19 40 34 24  5  8 46 11 30 27 38] 18
[39 45 51 23 20 12 32  4 14 43 10 28 26 36  3 29 53  9] 18
[15 37 13 42 17 25 16 31 18  2 41 22 48  1 49  7  6] 17
